Main Page Reference Manual Namespace List Compound List Namespace Members Compound Members File Members
Helper functions for within gdb
Functions
void const * cwdebug_watch (void const *ptr) __attribute__((unused))
Add a watch point for freeing ptr.
int cwdebug_alloc (void const *ptr) __attribute__((unused))
Print information about the memory at the location ptr.
Detailed Description
page_gdb
Function Documentation
cwdebug_alloc()
int cwdebug_alloc (void const * ptr)
Print information about the memory at the location ptr.
This function can be called from inside gdb. It can be used to figure out what/where some memory location was allocated. This is especially handy in large applications where about everything is dynamically allocated, like GUI applications.
References libcwd::type_info_ct::demangled_name(), libcwd::alloc_ct::description(), libcwd::libcw_do, libcwd::alloc_ct::size(), libcwd::alloc_ct::start(), libcwd::alloc_ct::time(), and libcwd::alloc_ct::type_info().
cwdebug_watch()
void const * cwdebug_watch (void const * ptr)
Add a watch point for freeing ptr.
This function can be called from inside gdb. After continuing the application, gdb will stop when the memory that ptr is pointing to is being freed.
References libcwd::libcw_do, and libcwd::alloc_ct::start().
Copyright © 2001 - 2004 Carlo Wood. All rights reserved.